### ISSUE TITLE
Nginx로 이미지 관리하기

### ISSUE THREAD

**Issue by JongDeug** [JongDeug/blog-backend#146]
## 📜 문제
서버 컨테이너 `uploads` 폴더에 이미지를 저장하게 되면 다시 배포했을 때 모두 초기화되는 문제가 생김 

## 🤔 고민
라즈베리파이에 이미지 폴더를 만든다고 치자. 서버 컨테이너와 환경이 다른데 어떻게 접근하지?

## ⭐ 해결
도커 컴포즈파일에서 **컨테이너와 호스트 머신 간 폴더 동기화** 설정이 가능하다는 사실을 알게 됨.

```yaml
  server: # Server 컨테이너
    container_name: blog-backend-server
    ...
    volumes:
      - /home/uploads/blog-backend:/app/blog-backend-server/uploads # 왼쪽 호스트, 오른쪽 컨테이너 경로 동기화
```

`/home/uploads/blog-backend` **폴더의 접근 권한을 변경**하고, Nginx를 활용해 **WAS(Web Application Server)까지 들어오지 않고도 이미지 조회 가능하게 만듦**
```
        location /uploads/ {
                alias /home/uploads/blog-backend/;
                try_files $uri $uri/ =404;
        }
```

- [참고 링크](https://velog.io/@snghyun331/Ubuntu-Nginx-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%84%9C%EB%B2%84-%EA%B5%AC%EC%B6%95Nginx%EB%A1%9C-%EC%A0%95%EC%A0%81%ED%8C%8C%EC%9D%BC-%EC%9A%94%EC%B2%AD%ED%95%98%EA%B8%B0)

## 🔥 대안
AWS S3 사용(공부 필요)
