### ISSUE TITLE
Github Actions 특정 파일 제외

### ISSUE THREAD

**Issue by JongDeug** [JongDeug/blog-backend#162]
## 📜 문제
README.md 파일을 변경하는데 Github Actions가 작동됨

## ⭐ 해결
```
# main branch push 시
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
```
